### ISSUE TITLE
Ignore certain anchor tags

### ISSUE THREAD

**Issue by tamb** [rumkin/pill#11]
Should be an option to ignore certain anchor tags

**Comment by rumkin** [comment]
I'd prefer not to leak into HTML with custom tags at least for the first version.There is shouleServe callback for thing like this, its' arguments list should be extended. Currently it accepts `url` as a single argument, there should be a link element as the second. Could you do this in your PR?

**Comment by rumkin** [comment]
Thanks for contribution!
