### ISSUE TITLE
Uncaught TypeError: at "onPopState" function

### ISSUE THREAD

**Issue by kayxean** [rumkin/pill#19]
Cannot read property 'scroll' of undefined at `window.scrollTo(0,e.state.scroll||0)`

**Comment by rumkin** [comment]
Rizky, could you provide more information about the bug to help reproduce it: browser version, pill version, link/source?

**Comment by usecdn** [comment]
I'm using the latest **Chrome browser**, maybe I just forced the component by combining **Pill** with [History.js](https://github.com/fromdeveloper/history.js)

then I found some features that didn't work. starting from "state: scroll" and "popstate".

**Comment by rizkysaskiaputra** [comment]
I'm using the latest **Chrome browser**, maybe I just forced the component by combining **Pill** with History.js

then I found some features that didn't work. starting from "`state:scroll`" and "`popstate`".

**Comment by rumkin** [comment]
Thanks. Pill and History competes for the History API control, what cause the error. I will think how to fix the conflict for awhile.

**Comment by rizkysaskiaputra** [comment]
I'm just manipulating "`pushState`" or "`replaceState`" and there really is a problem. maybe from **History.js** or **Pill**, I haven't found it yet.

**Comment by rumkin** [comment]
Pill definitely would conflict with History.js and it strongly recommended not to use them together.
