### ISSUE TITLE
Add my Jekyll theme to showcase or example

### ISSUE THREAD

**Issue by sharadcodes** [rumkin/pill#21]
Hi !
I've added pill to my Jekyll theme Dark Reader: https://github.com/sharadcodes/jekyll-theme-dark-reader. It would be great if you add it to showcase or as an example.
Thanks!

**Comment by rumkin** [comment]
Hi, Sharad. Thanks for using Pill and for giving a reference to it. I'm working on a website and better documentation and will add a link to your theme.

**Comment by sharadcodes** [comment]
> Hi, Sharad. Thanks for using Pill and for giving a reference to it. I'm working on a website and better documentation and will add a link to your theme.

Cool
