### ISSUE TITLE
custom events

### ISSUE THREAD

**Issue by tamb** [rumkin/pill#25]
Each stage of content fetching and rendering should offer namespaced events. 
like `pill.mounted` and the `detail` object contains the same data the hook would
This opens the door for other scripts to hook into pill without being in the same module.

**Comment by rumkin** [comment]
Agree this is useful enhancement. I wold like to see this with such syntax:

```
event-name = namespace ':' event
namespace = a-z
event = a-z-
```

Examples:

```
pill:mount
pill:ready
pill:complex-event
```

In my opinion it's closer to XML-namespaces which also are separated with the colon.
