### ISSUE TITLE
Pill vs alternatives

### ISSUE THREAD

**Issue by mustafa0x** [rumkin/pill#4]
Nice library! 👍 

There are a quite a few pjax (pushState + AJAX) and spf (Structured Page Fragments) libraries, so I was wondering what the main differences were between Pill and its alternatives (https://github.com/topics/pjax).

**Comment by rumkin** [comment]
The main benefit of Pill is its' size. I've compared it with [Pjax](https://github.com/MoOx/pjax) which is 6.9 KiB and [Turbolinks](https://github.com/turbolinks/turbolinks) which is 9.3 KiB. Pjax and Turbolinks were suggested by the readers in comments to [announcement post](https://www.reddit.com/r/javascript/comments/b6tu7e/pill_tiny_1_kib_library_to_add_dynamic_loading/) on Reddit.

**Comment by mustafa0x** [comment]
Thanks!

**Comment by tamb** [comment]
@mustafa0x I'd also note that the learning curve for this library is basically non-existent.  Could use some better documentation.  But otherwise it's great!
